//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.sales = new HashSet<sale>();
        }
    
        public int car_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public int prod_date { get; set; }
        public string colour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
        /*
        public static implicit operator car(car v)
        {
            throw new NotImplementedException();
        }*/
    }
}
