//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sale_id { get; set; }
        public int customer_id { get; set; }
        public int dealer_id { get; set; }
        public int car_id { get; set; }
        public Nullable<decimal> transaction_amount { get; set; }
        public Nullable<byte> on_company { get; set; }
    
        public virtual car car { get; set; }
        public virtual customer customer { get; set; }
        public virtual dealer dealer { get; set; }
    }
}
